- name: Configure nginx web server to pick the web page from our custom folder in CentOS
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  register: configured
  notify: 
  - Check if nginx is already running
  - Stop the nginx web server in CentOS if it is running already
  - Start the nginx web server in CentOS
