- name: Demonstrates invoking our Custom Ansible module
  hosts: all 
  tasks:
  - name: Invoke custom hello module
    hello: message="Hello Custom Ansible Module!"
    register: output

  - debug: var=output
