---
# handlers file for nginx
- name: Check if nginx is already running
  shell: curl localhost
  register: output
  ignore_errors: yes

- name: Stop the nginx web server in CentOS if it is running already
  when: output.rc == 0 
  shell: /usr/sbin/nginx -s stop

- name: Start the nginx web server in CentOS
  shell: /usr/sbin/nginx

- name: Restart the nginx web server in Ubuntu
  when: output.failed == true or configured.changed == true 
  shell:  service nginx restart