- name: This playbook will provision ansible node containers 
  hosts: localhost
  become: yes

  vars:
  - container_count: 5 

  tasks:
  - name: Install Python package installer in Fedora
    when: ansible_distribution == "Fedora"
    yum: name=python3-pip state=latest

  - name: Install Python package installer in Ubuntu 
    when: ansible_distribution == "Ubuntu"
    apt: name=python3-pip state=latest

  - name: Install Docker Python SDK which is required for docker_container ansible module
    shell: pip3 install docker-py 

  - name: Delete existing ubuntu containers
    shell: docker rm -f $(docker ps -aq -f "name=ubuntu" -f "name=centos")
    ignore_errors: yes

  - name: Provision ubuntu ansible node containers
    docker_container:
      image: tektutor/ubuntu-ansible-node:latest
      name:  "ubuntu-{{item}}"
      hostname: "ubuntu-{{item}}"
      ports:
        - "2{{item}}:22"
        - "8{{item}}:80"
    with_sequence: start=1 end="{{container_count}}" format="%03d"

  - name: Provision centos ansible node containers
    docker_container:
      image: tektutor/centos-ansible-node:latest
      name:  "centos-{{item}}"
      hostname: "centos-{{item}}"
      ports:
        - "3{{item}}:22"
        - "9{{item}}:80"
    with_sequence: start=1 end="{{container_count}}" format="%03d"
    tags:
    - centos
